server:
  port: 7802
spring:
  application:
    name: server-b
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/


feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 500 #断路器超时时间，默认1000ms

  threadpool:
    default:
      coreSize: 5  #并发执行的最大线程数，默认10
      maximumSize: 8  #最大线程数，默认10
      keepAliveTimeMinutes: 1  #空闲线程存活时间，默认一分钟
      maxQueueSize: -1  #最大队列数，默认为-1，-1不会排队，前程池满了就拒绝访问
      #      queueSizeRejectionThreshold: 5  #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝。因为maxQueueSize不能被动态修改，这个参数将允许我们动态设置该值。if maxQueueSize == -1，该字段将不起作用
      allowMaximumSizeToDivergeFromCoreSize: true

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 2000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1